services:
  mc:
    container_name: ucm_mc_server
    image: itzg/minecraft-server:java21
    tty: true
    stdin_open: true
    ports:
      - "25565:25565/tcp"
      - "19132:19132/udp"
    environment:
      # Treat them as system accounts
      UID: 999
      GID: 999

      # General settings
      VERSION: "1.21.8"
      EULA: "TRUE"
      TYPE: "PAPER"
      PAPER_CHANNEL: "experimental"
      MEMORY: "10240M"
      USE_MEOWICE_FLAGS: "true"
      ICON: "/icon.png"
      OVERRIDE_ICON: "true"

      # Environment variables within configs
      REPLACE_ENV_VARIABLES: "true"
      REPLACE_ENV_VARIABLES_EXCLUDES: |
        data/plugins/Geyser-Spigot/custom-skulls.yml
        data/plugins/CoreProtect/language.yml
        data/plugins/LuckPerms/translations

      # Environment variables for database connections
      ENV_VARIABLE_PREFIX: "CFG_"
      CFG_DB: mc
      CFG_DB_HOST: database
      CFG_DB_USER: ${MARIADB_USER}
      CFG_DB_PASSWORD: ${MARIADB_PASSWORD}

      # Patch both bukkit and spigot configs
      PATCH_DEFINITIONS: /patches/bukkit-spigot-config.json

      # Maintain server seed
      # SEED: "8312171185849629204"

      # Game settings
      MAX_PLAYERS: 30
      MODE: "survival"
      DIFFICULTY: "normal"

      # Plugins
      MODRINTH_PROJECTS: |
        chunky
        coreprotect
        luckperms
        terra:beta
        viaversion:beta
        bolt
        distant-horizons-support

      # Direct plugin sources
      PLUGINS: |
        https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
        https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
        https://ci.lucko.me/job/spark/504/artifact/spark-bukkit/build/libs/spark-1.10.154-bukkit.jar
        https://github.com/Bleep0/AntiBookBan/releases/download/1.3/AntiBookBan.jar

      # Yes, Noelle is server op
      OPS: |
        Winter_Melody
        Anarele

      RCON_CMDS_STARTUP: |
        gamerule playersSleepingPercentage 0
      
      # Whitelist
      WHITELIST_FILE: /whitelist.json
      ENFORCE_WHITELIST: "true"
      ENABLE_WHITELIST: "true"

      # server.properties override 
      MOTD: "UC MERCED SERVER YAAAAAAY"
      NETWORK_COMPRESSION_THRESHOLD: 256
      SIMULATION_DISTANCE: 6
      VIEW_DISTANCE: 8
      ENABLE_STATUS: "true"
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: mc-health
      start_period: 1m
      interval: 5s
      retries: 20
    volumes:
      - "${DATA_LOCATION}:/data"
      - "./patches/bukkit-spigot-config.json:/patches/bukkit-spigot-config.json"
      - "./whitelist.json:/whitelist.json"
      - "./configs:/config"
      - "./mc-plugins:/plugins"
      - "./server-icon.png:/icon.png"
    restart: always

  database:
    container_name: ucm_mc_database
    image: mariadb:lts-noble
    ports:
      - "3306:3306"
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_AUTO_UPGRADE: ${MARIADB_AUTO_UPGRADE}
      MARIADB_RANDOM_ROOT_PASSWORD: ${MARIADB_RANDOM_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - "${DB_DATA_LOCATION}:/var/lib/mysql:Z"
    restart: always
