server {
  listen 443 ssl;
  server_name  prometheus-ucm-mc.mineced.org;
  
  ssl_certificate /etc/letsencrypt/live/prometheus-ucm-mc.mineced.org/fullchain.pem; # managed by Certbot
  ssl_certificate_key /etc/letsencrypt/live/prometheus-ucm-mc.mineced.org/privkey.pem; # managed by Certbot
  include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
  ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

  resolver 127.0.0.11 valid=30s;

  location ^~ /.well-known/acme-challenge/ {
      default_type "text/plain";
      root /var/www/letsencrypt;
  }

  location / {
    auth_basic           "admin";
    auth_basic_user_file /etc/nginx/.htpasswd;

    proxy_pass http://prometheus:9090;
  }
}

server {
    if ($host = prometheus-ucm-mc.mineced.org) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    location /ping {
      return 200 "pong";
    }

    listen 80;
    server_name  prometheus-ucm-mc.mineced.org;
    return 404; # managed by Certbot
}